export const  TODO_GET_START = " TODO_GET_START"
export const  TODO_GET_SUCCESS = " TODO_GET_SUCCESS"
export const  TODO_GET_ERROR = " TODO_GET_ERROR"

export const  TODO_ADD_START = " TODO_ADD_START"
export const  TODO_ADD_SUCCESS = " TODO_ADD_SUCCESS"
export const  TODO_ADD_ERROR = " TODO_ADD_ERROR"

export const  TODO_CHANGE_START = " TODO_CHANGE_START"
export const  TODO_CHANGE_SUCCESS = " TODO_CHANGE_SUCCESS"
export const  TODO_CHANGE_ERROR = " TODO_CHANGE__ERROR"

