export const  TODO_GET_START = " TODO_GET_START"
export const  TODO_GET_SUCCESS = " TODO_GET_SUCCESS"
export const  TODO_GET_ERROR = " TODO_GET_ERROR"

export const  TODO_POST_START = " TODO_POST_START"
export const  TODO_POST_SUCCESS = " TODO_POST_SUCCESS"
export const  TODO_POST_ERROR = " TODO_POST_ERROR"

export const  TODO_DELETE_START = " TODO_DELETE_START"
export const  TODO_DELETE_SUCCESS = " TODO_DELETE_SUCCESS"
export const  TODO_DELETE_ERROR = " TODO_DELETE_ERROR"


export const  TODO_CHANGE_START = " TODO_CHANGE_START"
export const  TODO_CHANGE_SUCCESS = " TODO_CHANGE_SUCCESS"

export const  TODO_CHANGE_ERROR = " TODO_CHANGE__ERROR"



export const  TODO_SUCCESS_DELETE = " TODO_SUCCESS_DELETE"
